### ISSUE TITLE
performance?

### ISSUE THREAD

**Issue by laurentopia** [alelievr/NodeGraphProcessor#100]
I see `using linq;` and I think allocation and performance killer
how are performance in real application?

**Comment by alelievr** [comment]
Good enough for what I tested, in the editor, the rendering is by far the bottleneck (especially when you render fields in the nodes, which is very slow in Unity even with the GraphView LOD system).
I didn't profile in playmode without the editor yet, it's on my roadmap. But I'd be surprised if the result were bad, most of the linq stuff is done only for the editor and not the runtime version.

**Comment by laurentopia** [comment]
oh okok thanks!
