### ISSUE TITLE
Question : UIToolkit for runtime

### ISSUE THREAD

**Issue by felixcantet** [alelievr/NodeGraphProcessor#102]
Hi,

UIElement for runtime is currently in preview state. Do you think a Runtime version of NodeGraph Processor could work? I'm beginning a school project and I plan to use NodeGraph Processor to build a texture editor in the style of Substance Designer, and I would be very interested in building a standalone version of the editor, so it need runtime support. I didn't investigate the UIToolkit Builder at the moment, so I don't know how it works and how it could fit with your plugin.

Thank you ! 

Sorry for my bad english

Félix

**Comment by TeorikDeli** [comment]
I think Unity doesn't support GraphView for runtime (yet) and NodeGraphProcessor is based on that. If Unity supports that in the future, most of the Node Graph Processor could be work on runtime with minimal changes I believe. Buuut, I might be wrong 😅

**Comment by felixcantet** [comment]
Thank you,

I hope i will be possible in the future ! Be able to build standalone app with this awesome API would be a very interesting feature.

**Comment by andybak** [comment]
Just to point out UI Elements (or whatever it's called now) currently does work in runtime: https://medium.com/@raynor85/new-unity-uielements-runtime-system-how-to-use-it-now-f560c4cb22d2

Not sure whether thats still preview/alpha - and I recall it's screen-space only (with world-space support looking like a 2021 thing).

**Comment by felixcantet** [comment]
Thank you for precision.

It's currently working for runtime, but the NodeGraph API use intensively Editor API (as exemple the NodeView class is in UnityEditor namespace), so I don't know how it could be use in runtime context at the moment

**Comment by andybak** [comment]
> (as exemple the NodeView class is in UnityEditor namespace),

Sigh. Such foresight from our lords and masters. (Not aimed at you in the slightest @alelievr )

**Comment by alelievr** [comment]
😅 

I can confirm that GraphView is an editor only feature right now (and there are no plan to support a runtime version). Because NodeGraphProcessor uses GraphView for all the display stuff, it means that it's not possible to use it as it is in the runtime.

It might be possible to re-build a runtime version with UIElements from scratch though but it's a lot of work.

**Comment by felixcantet** [comment]
Thank you for clarification !
