### ISSUE TITLE
NodeView doesn't show changed ports list

### ISSUE THREAD

**Issue by mihvotak** [alelievr/NodeGraphProcessor#106]
There is a mistake in BaseNodeView::RefreshPorts:UpdatePortViewWithPorts.
When ports.Count > 0 and portViews.Count > 0 and portViews.Count < ports.Count, this function updates old ports, but doesn't create new portViews.
Solution: after line
```
		SyncPortCounts(new NodePort[]{}, portViews);
```
add 2 new lines
```
	else if (portViews.Count != ports.Count)
		SyncPortCounts(ports, portViews);
```

**Comment by alelievr** [comment]
Thanks for the bug report, I pushed your fixed here: https://github.com/alelievr/NodeGraphProcessor/commit/91ddb20f4f5caedb47e2c10bb648c89c4027bfcc
