### ISSUE TITLE
[New feature request] Create custom EdgeView

### ISSUE THREAD

**Issue by gelonsoft** [alelievr/NodeGraphProcessor#108]
I need to customize EdgeView (change colors, add new features).
Now in your base classes you use direct creation of EdgeView and I can't create instance of my custom EdgeView instead of original EdgeView.

**Comment by gelonsoft** [comment]
Created pull request https://github.com/alelievr/NodeGraphProcessor/pull/109

**Comment by alelievr** [comment]
Hello,

That's indeed a good feature to have and thanks for taking the time to make a pull request :) 
I left a few comments on the PR

**Comment by alelievr** [comment]
Closing as the PR was merged
