### ISSUE TITLE
BaseNode Inheritance & Serialization

### ISSUE THREAD

**Issue by LudiKha** [alelievr/NodeGraphProcessor#111]
Hi, I'm having a setup where I have multiple levels of inheritance in my nodes, and each level has fields I want serialized.

Currently, only inherited fields tagged with an input/output attribute will show up, as the binding flag `DeclaredOnly` is applied.

Might I suggest that the public BaseNode members that don't need to be visualized (position, GUID, etc.) are made into properties, or receive a `[HideInInspector]` tag, such that we can leverage inheritance in our views more easily?

Cheers & keep up the good work

**Comment by alelievr** [comment]
Hello,

I think it's a good idea to mark everything that is not supposed to be visible with `[HideInInspector]` and then remove the `DeclaredOnly` flag. I'll do it after I finish the work on serialization

**Comment by LudiKha** [comment]
Cool! That's currently the fix I added in. Good to hear you're working on serialization. Looking forward to the result. Closing this 👍
