### ISSUE TITLE
[Feature] Persistent output nodes

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [alelievr/NodeGraphProcessor#115]
It would be useful to define nodes that can not be removed from the graph using the editor. This would allow us to define "output" nodes that exist in every graph and serve as a reliable entry point for every graph (similar to the material output node of shader graph). 

This feature could be implemented using a virtual property in `BaseNode`
```c#
public virtual bool IsPersistant => false;
```

or even a custom attribute, however, a virtual property would allow runtime changes to the persistence of the node and would work better with inheritance.

**Comment by LudiKha** [comment]
I'd also like this!

**Comment by alelievr** [comment]
Hello,

In this example, I'm using the Capabilities of graphview to create such behavior (for an Output node that the user can't delete): https://github.com/alelievr/Mixture/blob/master/Packages/com.alelievr.mixture/Editor/Views/OutputNodeView.cs#L23

Do you think you could use this feature for what you need or does the API needs to be on the node part and not the view?

**Comment by FreshlyBrewedCode** [comment]
Thanks! I did not know about `Capabilities.Deletable`. I think setting the flag in the view is just fine for most cases. Having it as part of the `BaseNode` api would just be more convenient. 
I think it would be great to include an example for this in the project or mention it in the docs since this is a common behavior seen in many different node based systems.

Feel free to close this issue or keep it around/reopen if you think it could be added to the api in the future :)

**Comment by alelievr** [comment]
It makes sense to add this API in the BaseNode class so I added it here: https://github.com/alelievr/NodeGraphProcessor/commit/03452ed5ebc5eac0a7bced8f825b1013b43a1d63

Along with an output node example :)
