### ISSUE TITLE
[Bug] Inconsistent field drawer positions

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [alelievr/NodeGraphProcessor#116]
There seem to be inconsistencies with the position of the field drawer when using `[ShowAsDrawer]`, especially for inherited nodes. I assume the intended behavior is that a drawer is always shown next to the port it belongs to.

1. Using `[SerializeField]` on a field that does not have a field drawer causes an offset on following field drawers:
![image](https://user-images.githubusercontent.com/11772241/104122587-352eae80-5346-11eb-95a5-9f688fbf57e3.png)
(drawer belongs to "In 2" but is drawn at "In 1")
```c#
[System.Serializable, NodeMenuItem("Test/Simple")]
public class SimpleNode : BaseNode
{
    [SerializeField, Input("In 1")]
    public Quaternion value;
    
    [SerializeField, ShowAsDrawer, Input("In 2")]
    public float value2;
}
```

2. Inheriting inputs from a base class causes offsets on field drawers:
![image](https://user-images.githubusercontent.com/11772241/104122715-fea56380-5346-11eb-8670-f6bb6a0094da.png)
In this case "In 1" does not even use the `[SerializeField]` attribute:
```c#
[System.Serializable, NodeMenuItem("Test/Parent")]
public class ParentNode : BaseNode
{
    [Input("In 1")]
    public float value;
}

[System.Serializable, NodeMenuItem("Test/Inherited")]
public class InheritedNode : ParentNode
{
    [SerializeField, ShowAsDrawer, Input("In 2")]
    public float value2;
}
```

This behavior does not affect the functionality of the drawer but is still confusing when working with nodes with multiple inputs. 

### Version Info
- NodeGraphProcessor 0.10.3
- Unity: 2020.2.0f1

**Comment by alelievr** [comment]
Thanks for the detailed report, much appreciated :)
