### ISSUE TITLE
[Feature] Colored nodes

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [alelievr/NodeGraphProcessor#118]
I found the new [color modes feature of shader graph](https://docs.unity3d.com/Packages/com.unity.shadergraph@6.9/manual/Color-Modes.html) really useful when dealing with an increasing number of nodes (also it just looks cool :) ). I don't know if there is any "official" graph view api to handle colors but it is very easy to add by simply adjusting the border color of the `titleContainer` in `BaseNodeView`. Here is the result:

![image](https://user-images.githubusercontent.com/11772241/104519532-dee99600-55f9-11eb-9bea-670e32fc3ea3.png)

Maybe this feature could be added as part of the api. The way I implemented it is using a virtual property in `BaseNode` (just like `name`) because it allows me to override it in the base class of a specific node type and adjust the color for that entire category of nodes in a single place.

Let me know if that sounds like a good addition and I can submit a PR.

**Comment by alelievr** [comment]
That's definitely a great addition to NodeGraphProcessor :)

I don't think there are any standard API to handle this so a custom solution is definitely okay.
