### ISSUE TITLE
Bug: Inconvenient error logging

### ISSUE THREAD

**Issue by dsmiller95** [alelievr/NodeGraphProcessor#119]
I'm building some custom nodes, and the ExceptionToLog handler prevents unity from recognizing source links in the logs. I think using Debug.LogException would fix this.

Here's an example. In this case the origin of the error in my code is highlighted in red, but the first linked source file is ExceptionToLog.cs
![image](https://user-images.githubusercontent.com/3212309/104797857-25203000-5787-11eb-9803-6f09d52e221e.png)

**Comment by alelievr** [comment]
Yeah, I agree, it's much better with LogException :)

Thanks for the pull request!
