### ISSUE TITLE
y position of the node

### ISSUE THREAD

**Issue by Ruchi12377** [alelievr/NodeGraphProcessor#122]
Hello.

First I was writing code to add the minimum number of nodes needed from the script to the graph, and then I noticed that the y-position was inverted.
In the video below, you can see how the y-position increases when the node is moved down and decreases when the node is moved up.
Is this a GraphView or NodeGraphProcessor specification?
Is this a bug in GraphView or NodeGraphProcessor?
Please check.

https://user-images.githubusercontent.com/65443794/105641726-ff9ecf00-5ec8-11eb-9e13-ca5769e481cf.mp4

**Comment by TeorikDeli** [comment]
This is actually normal. Because it shows Left and Top margins (Like in CSS' left and top properties). As far as I remember, these X (Left) and Y (Top) properties are not relative to the window, but relative to parent graph view.

**Comment by Ruchi12377** [comment]
Our doubts were lifted
Thank you very much.
(Translation from Japanese)
