### ISSUE TITLE
Selecting enum dropdown drags node

### ISSUE THREAD

**Issue by cr4yz** [alelievr/NodeGraphProcessor#123]
When selecting an enum in node it drags the node and has to be repositioned.

https://streamable.com/nnf101

**Comment by alelievr** [comment]
Hello,

I already experienced this issue with ShaderGraph blackboard, I think this is a GraphView bug as it was reported here: https://issuetracker.unity3d.com/issues/hdrp-graph-inspector-window-sticks-to-the-mouse-cursor-on-changing-any-dropdown-value-in-node-settings

**Comment by alelievr** [comment]
Issue fixed by Graphview team for 2021.2.X
