### ISSUE TITLE
[Feature Request] Vertical Graphs

### ISSUE THREAD

**Issue by arajar** [alelievr/NodeGraphProcessor#124]
Hi!

I'm currently creating a Behaviour Tree system and while checking various node graph packages from the community I came up with this one, as it's very promising. I was wondering if there is a way to have a vertical graph layout like this one ![](https://nodecanvas.paradoxnotion.com/wp-content/uploads/sites/4/2015/12/BTs-1024x321.png)

Thanks a lot.

**Comment by alelievr** [comment]
Hello,

sadly it's not currently possible. I'll see if I can add this quickly as it shouldn't be too hard to do

**Comment by arajar** [comment]
That's awesome, @alelievr!
Thank you so much :)

**Comment by alelievr** [comment]
I added the code and an example at 2b8e52e6c30d27d9a2f00b4c6dc56cf81658a0c6

You should now be able to create vertical graphs using the `[Vertical]` on a field like in this example:

```CSharp
[System.Serializable, NodeMenuItem("Custom/Vertical")]
public class VerticalNode : BaseNode
{
	[Input, Vertical]
    public float                input;

	[Output, Vertical]
	public float				output;

	public override string		name => "Vertical";

	protected override void Process()
	{
	    output = input * 42;
	}
}
```

![image](https://user-images.githubusercontent.com/6877923/106968910-199ea400-674a-11eb-8f0d-76230c3e10c5.png)
