### ISSUE TITLE
Connection not deleted when node input or output as Vertical Attribute 

### ISSUE THREAD

**Issue by jejelite** [alelievr/NodeGraphProcessor#127]
When a node output or input has the Vertical Attribute and you delete the node connected to it the connection is not automatically  remove. (Can be produce and the vertical example in the master)

**Comment by alelievr** [comment]
Hello,

Thanks for the bug report, the issue should be fixed at 118429ad619767c21c1dadee93e462ffcd49f718
![VerticalDelete](https://user-images.githubusercontent.com/6877923/107282326-1a417e00-6a5b-11eb-91e4-e212acf41988.gif)
