### ISSUE TITLE
Is there a way to guarantee ordering of inputs on a node?

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#131]
I have a derived class where one of my inputs in the derived class is above the inputs in the base class. Ideally I would like derived class inputs to always be below the base class

**Comment by alelievr** [comment]
Right now, it's not possible, but it's a good feature request and there are already a couple of TODO in the code talking about this

**Comment by alelievr** [comment]
I fixed the sorting code, now inherited fields will be displayed first in the node as it makes more sense. There's also a new function `OverrideFieldOrder` that you can override to do your custom sorting
https://github.com/alelievr/NodeGraphProcessor/commit/65587d6922acd6cea67a455bff8aa1b130d5932c
