### ISSUE TITLE
Is it possible to add a description to nodes?

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#132]
Sorry for all the questions! I tried searching, but didn't see a way to add descriptions to a node on tooltip or something. Would be very useful once you get a lot of custom nodes added in

**Comment by alelievr** [comment]
All the Unity UIElements have a tooltip field if that's what you're looking for. When you assign the tooltip of a node view it shows up below the node like this:
![image](https://user-images.githubusercontent.com/6877923/107886947-3897f580-6f03-11eb-99b7-f89f85c3cc8d.png)
https://docs.unity3d.com/ScriptReference/UIElements.VisualElement-tooltip.html

**Comment by emrys90** [comment]
How do you get it below the node? Do you need a custom node view class for each node to give it a tooltip, or is there some attribute that can be applied to a node?

Basically I'm looking for a way to have an on hover tooltip if possible, but always below works too for now, and ideally a way to see the tooltip in the create node menu too

**Comment by alelievr** [comment]
Yeah, with a custom view. I recommend you create a base custom view that all your node inherit, this will give you a lot more control over your nodes. Like I did in my Mixture project: https://github.com/alelievr/Mixture/blob/master/Packages/com.alelievr.mixture/Editor/Views/MixtureNodeView.cs

**Comment by alelievr** [comment]
For the node create menu I don't think it's possible to have a tooltip in it. I'm using the [ISearchWindowProvider](https://docs.unity3d.com/2019.3/Documentation/ScriptReference/Experimental.GraphView.ISearchWindowProvider.html) for it and it doesn't seem to support tooltips

**Comment by emrys90** [comment]
Is it not possible to do this in a way that doesn't require a custom node view, ie using a Description attribute that is put on your classes that derive from BaseNode?

For the search window, is it possible to add a second line of text in a smaller font or something? So you could place the description below it

**Comment by alelievr** [comment]
> Is it not possible to do this in a way that doesn't require a custom node view, ie using a Description attribute that is put on your classes that derive from BaseNode?

You can do this, but you'll have to modify NodeGraphProcessor to add it in this case.

> For the search window, is it possible to add a second line of text in a smaller font or something? 
No idea, I never tried. But the API seems very limited (i.e. you can only give a `GUIContent` for an item and that's it) so it's unlikely that it'll work.

**Comment by emrys90** [comment]
Thanks, I just added it in using a custom node view
