### ISSUE TITLE
Why does BaseGraphWindow.InitializeGraph call Resources.UnloadAsset on the previous graph?

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#133]
This took a while for me to track down lol. I was having an issue where SerializeFields for BaseGraph would lose their references to a graph, and it was because of that call. Eventually I figured out that it lost their reference if I opened a different graph, and tracked it down to that line of code

**Comment by alelievr** [comment]
Originally it was to free the memory of the graph and everything temporary in it but now the code has evolved in a different way, so I don't think it's necessary anymore

**Comment by alelievr** [comment]
Removed it in https://github.com/alelievr/NodeGraphProcessor/commit/2a6bfd56b6764d924deafea2cc2412dd06dce536
