### ISSUE TITLE
Is there a way to limit an output to only being connect to one input?

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#135]
I'm building a custom process flow where you specify the order of execution based on connecting an output to an input. I'm using this for being able to build a behavior tree. Is there a way to limit an output to only having one connection?

**Comment by alelievr** [comment]
Yes, it's the `allowMultiple` parameter in the Output attribute is made for that: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Graph/Attributes.cs#L36

**Comment by emrys90** [comment]
Thanks! Can't believe I missed that haha
