### ISSUE TITLE
Vertical nodes not saving data unless graph is closed

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#136]
I'm having an issue where you if delete a vertical node connection, then any changes to the graph will not be saved to disk unless you close the graph window

**Comment by alelievr** [comment]
Humm, it seems to be working pretty well for me. 

https://user-images.githubusercontent.com/6877923/109427870-a14b9b80-79f4-11eb-9af4-f44aa4978453.mp4

Note that if you want the graph to be written to the disk when you hit ctrl-s in unity, you need to add these lines in your graph view code:
```Csharp
			RegisterCallback<KeyDownEvent>(e => {
				if (e.keyCode == KeyCode.S && e.actionKey)
					SaveGraphToDisk();
			});
```
