### ISSUE TITLE
Vertical nodes drawer position incorrect

### ISSUE THREAD

**Issue by emrys90** [alelievr/NodeGraphProcessor#139]
I have a SerializeField on a Vertical node, and it puts the field drawer in the wrong spot
![image](https://user-images.githubusercontent.com/20632855/107885330-3613ac80-6ebf-11eb-888d-e4114a83aa2d.png)

**Comment by alelievr** [comment]
Thanks for the bug report, I fixed the issue in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/e017b1da755077a0837ffecd08ae7e7bf2af2dab

**Comment by emrys90** [comment]
I copy pasted the code change you made in that commit, but it's still offcenter for me. Was there something else I needed to do too?

**Comment by emrys90** [comment]
From my testing it appears like it needs an extra AddEmptyField to move it down one so its aligned, but your change would make it not add them instead, so I think the bug I am running into is unrelated to the one you fixed

**Comment by alelievr** [comment]
Yeah, indeed, can you share the code of your node so I can repro in local?

**Comment by emrys90** [comment]
In a base class I have
`
        private static readonly PortData[] _inputPorts = new PortData[]
        {
            new PortData { displayName = "Enter", displayType = typeof(Link), acceptMultipleEdges = true, vertical = true }
        };

        [Input(name = "Enter"), Vertical]
        protected List<Link> _enter;

        [CustomPortBehavior(nameof(_enter))]
        public IEnumerable<PortData> GetPortsForInputs(List<SerializableEdge> edges)
        {
            return _inputPorts;
        }

        [CustomPortInput(nameof(_enter), typeof(Link), allowCast = true)]
        public void GetInputs(List<SerializableEdge> edges)
        {
            _enter = null;
        }
`

And in a derived class I have
`
        [Input(name = "Message"), SerializeField]
        private string _message;
`

**Comment by alelievr** [comment]
I took your example but couldn't reproduce with latest master:
![image](https://user-images.githubusercontent.com/6877923/109427548-29c93c80-79f3-11eb-9aaa-0ed7de49c4b4.png)


Can you check that you haven't some custom USS properties that would mess up with the layout?
