### ISSUE TITLE
Ports glitch when undoing a scene

### ISSUE THREAD

**Issue by notargs** [alelievr/NodeGraphProcessor#150]
- Open NodeGraphProcessor#1.0.1 in Unity2020.2.0f1
- Open an example graph(e.g. BasicExample.asset)
- Change scene(e.g. Duplicate DirectionalLight)
    - ![image](https://user-images.githubusercontent.com/3889597/113376704-4cad8e80-93ad-11eb-9ec5-4cc408cde390.png)
- Undo by Ctrl + Z or edit menu
    - ![image](https://user-images.githubusercontent.com/3889597/113376559-f93b4080-93ac-11eb-848f-79dd2c2cdeef.png)
- Ports multiply
    - ![image](https://user-images.githubusercontent.com/3889597/113376307-5d113980-93ac-11eb-82e9-d0eccd83f215.png)

**Comment by alelievr** [comment]
Hello, Thanks for the bug report :) 

This issue should be fixed by this commit: https://github.com/alelievr/NodeGraphProcessor/commit/bea17d70217f44509c30086ec04a4cfbe1836751
It will be available in the version 1.1.0 that will be released soon
