### ISSUE TITLE
Node Inspector

### ISSUE THREAD

**Issue by wildhevire** [alelievr/NodeGraphProcessor#152]
Is this possible to view serialized object that associated to node in inspector?  Just like Animator window

**Comment by alelievr** [comment]
Hello, I'm not sure which feature of the Animator window you refer to, can you post a screenshot?
Or are you talking about the debug mode in the editor?
![image](https://user-images.githubusercontent.com/6877923/114630067-0bc14e00-9cba-11eb-808e-34bf4977dd6e.png)

**Comment by wildhevire** [comment]
![image](https://user-images.githubusercontent.com/9078000/115109202-8cc06400-9f9e-11eb-8f23-863bc353b2d8.png)
I mean like this, the node displaying some high level properties but when it selected some detailed one appear in inspector window

**Comment by alelievr** [comment]
Yes, it's possible. Here is an example of how to show properties in the inspector when you select a node: [InspectorNode.cs](https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/DefaultNodes/Nodes/InspectorNode.cs).

You can use the `ShowInInspector` attribute on a field to only display them in the inspector window. For anything more advanced, you can create a node view script and add a bool parameter in the Enable function like here: https://github.com/alelievr/Mixture/blob/master/Packages/com.alelievr.mixture/Editor/Views/MixtureNodeView.cs#L63

When you do so, the Enable function will be called multiple times by either the node or the inspector to generate the visual content. So you can do a custom UI only visible in the inspector just with a condition on the `fromInspector` boolean

**Comment by wildhevire** [comment]
Thanks, it's help a lot, btw
I found some issue here
It might came from unity side but i just edit your string node example to check the attribute but its fixed itself before i realized
![image](https://user-images.githubusercontent.com/9078000/115156840-815d5d80-a0b0-11eb-884d-a34fa63d110c.png)
