### ISSUE TITLE
Is there field drawer for arrays/or lists?

### ISSUE THREAD

**Issue by ivankuzev** [alelievr/NodeGraphProcessor#154]

**Comment by alelievr** [comment]
It's not available by default but you can create one with the FieldDrawer attribute.

This attribute allows you to create a custom view for a given type (in you case a list of objects) that can then be displayed as a drawer on the node or in it's body.

There is an example of FieldDrawer here:
https://github.com/alelievr/Mixture/blob/master/Packages/com.alelievr.mixture/Editor/Utils/MixtureMeshDrawer.cs#L9

**Comment by ivankuzev** [comment]
Thanks for the example, I wish had found it 5 days ago. Really needed it then. I hope when you make one you make it as generic as possible.
