### ISSUE TITLE
Ports & node edges disappearing without error

### ISSUE THREAD

**Issue by LudiKha** [alelievr/NodeGraphProcessor#155]
Node edges and ports keep disappearing in my graphs since installing the new serialization update, without any error messages being thrown.

![image](https://user-images.githubusercontent.com/56917574/114784864-180ddf80-9d7c-11eb-96f3-c98ae6c5d2bc.png)

I am using Odin Inspector, but otherwise a pretty much unmodified version of NodeGraphProcessor.
Would appreciate any help!

**Comment by LudiKha** [comment]
For reference, this is how things look after duplicating the nodes.
![image](https://user-images.githubusercontent.com/56917574/114785156-894d9280-9d7c-11eb-84bd-48cca4a09187.png)

They return to their correct state when copying nodes, but the graphs unfortunately keep breaking.

**Comment by StanislavBotev** [comment]
Have the same - restarting the unity editor fixes it. Happens each time we edit any of the node files.

**Comment by alelievr** [comment]
Hello, which version of NGP are you using? I recently fixed a bug that may be related to this issue (https://github.com/alelievr/NodeGraphProcessor/commit/bea17d70217f44509c30086ec04a4cfbe1836751 and https://github.com/alelievr/NodeGraphProcessor/commit/a926eee011f9e0049cbe2c6a77c76658f1a4baec).

And I'm not able to reproduce the issue by changing the scripts of nodes, do you know any other way of causing the issue?

**Comment by LudiKha** [comment]
Hi! I'm on the latest of the releases. I'll try that latest commit  a926eee and cehck back.

**Comment by ivankuzev** [comment]
this is almost a sure way to cause it on my end. 
1. create a graph with some nodes.
2. close the graph
3. go to the node script of one of them and add/remove some ports.
4. open graph again

**Comment by alelievr** [comment]
That's really weird, I can't repro with these steps on my project. Do you mind sending me a repro project so I can debug the issue?

https://user-images.githubusercontent.com/6877923/116601793-2a1a8100-a92b-11eb-8180-8cf303e837d2.mp4

**Comment by ivankuzev** [comment]
Yeah i tried with your code and i cant either, looks like i messed up something during the integration with our main project, or with the 5+ drawers that i made. But i cant give you the main project sorry. Will try to hunt the bug, but so far i only know that it has something to do wwith some dictionary in node editor view when initializing the graph. will teall you i f i made any progress.
________________________________

**Comment by CyberJohnJohn** [comment]
Same issue when changing between graphs and sometimes when I make changes to the Nodes or Node views. I think it is somehow related to the meta files. It is fixed if I close and re open Unity

**Comment by ivankuzev** [comment]
This issue seems to have been fixed for me(and team) since about a week ago. One guy from the team still loses groups-> nodes references so we are not using groups. Don't groups serialize the same way as edges?

**Comment by LudiKha** [comment]
Issue was fixed for me too since the last update! 👍 

@alelievr feel free to close this if you feel it's been sufficiently adressed

**Comment by alelievr** [comment]
Nice!

I think it was probably this commit that fixed the issue: https://github.com/alelievr/NodeGraphProcessor/commit/7eae53b1354fc30458427d08efcef7c1f268df2b

Wasn't planned but nice side effect :)

**Comment by rhys-vdw** [comment]
I'm having this issue on 1.3.0
