### ISSUE TITLE
save problem

### ISSUE THREAD

**Issue by ivankuzev** [alelievr/NodeGraphProcessor#156]
I seem to be having some save(i think) related problem when i am editing a graph and i switch out of the editor tab to another one(for example to start dragging in a prefab) it sometimes loses last about 10 seconds of edits to the graph. Is that something that have caused maybe or a known issue. Also is it avoidable (Besides using the "Save Asset" option every time).

**Comment by alelievr** [comment]
Hello,

I'm not sure to understand how to repro the issue, when you switch from the graph tab to another one, does it closes the graph window?
