### ISSUE TITLE
GetNodeViewTypeFromType return wrong node view

### ISSUE THREAD

**Issue by HartMagic** [alelievr/NodeGraphProcessor#157]
'GetNodeViewTypeFromType' in 'NodeProvider' return first node view passed the check (IsSubclassOf), but it can be wrong type if using inheritance node view classes.
For example:
- node class MyCustomNode : BaseNode
- node class MyChildCustomNode : MyCustomNode
- node view class MyCustomNodeView : BaseNodeView
- node view class MyChildCustomNodeView : MyCustomNodeView

I expect 'GetNodeViewTypeFromType' return MyChildCustomNodeView for MyChildCustomNode but it return MyCustomNodeView for this class.

Solution:
`public static Type GetNodeViewTypeFromType(Type nodeType)
		{
			Type	view;

			if (nodeViewPerType.TryGetValue(nodeType, out view))
				return view;

			Type baseType = null;

			// Allow for inheritance in node views: multiple C# node using the same view
			foreach (var type in nodeViewPerType)
			{
				// Find a view (not first fitted view) of nodeType
				if (nodeType.IsSubclassOf(type.Key) && (baseType == null || type.Value.IsSubclassOf(baseType)))
				{
					baseType = type.Value;
				}
			}
			
			if (baseType != null)
				return baseType;

			return view;
		}`

Please fix it, thx :)

**Comment by alelievr** [comment]
Thanks for the fix, I overlooked that issue :) 
Fix included in https://github.com/alelievr/NodeGraphProcessor/commit/5a34268661276b6f342057d87196272633f7e5f6
