### ISSUE TITLE
Accessing to connected nodes

### ISSUE THREAD

**Issue by m3rt32** [alelievr/NodeGraphProcessor#16]
I am trying to access to connected nodes in order to only process them but when I do something such as `nodes.GetOutputNodes()` it always return 0 elements. So I am unable to trace connections. Is there a way of doing it ?

**Comment by alelievr** [comment]
I just tested it and it worked for me, from which context are you calling this function ?
Also, looking at the code of the function, it is rather simple:
```csharp
		public IEnumerable< BaseNode > GetOutputNodes()
		{
			foreach (var port in outputPorts)
				foreach (var edge in port.GetEdges())
					yield return edge.inputNode;
		}
```
You can try looking at the number of edges connected in the `outputPorts` to debug

**Comment by m3rt32** [comment]
Hey there, I switched to `graph.edges` solution but _GetOutputNodes_ doesn't work for me.
I am trying to access it through my processor script.
