### ISSUE TITLE
Moving node scripts between assemblies breaks graphs

### ISSUE THREAD

**Issue by LudiKha** [alelievr/NodeGraphProcessor#161]
Whenever I move a node script between different assemblies, I get the following error:

![image](https://user-images.githubusercontent.com/56917574/118127089-84224880-b3f9-11eb-9426-b14d9dff31ce.png)

"Unknown managed type referenced: ..."

For this to happen, you only need to move a script around from one assembly to the next in the project view. The type, and .meta file have remained unchanged. 

Luckily I'm fairly early in my data processing workflow so it didn't wreck anything. Though I would consider this a rather severe issue/limitation as it leads to full data loss of a graph asset, especially considering in a Unity workflow, moving scripts around or renaming them is going to be very common.

**Comment by alelievr** [comment]
Hello,

Unfortunately, this is one of the drawbacks of the new serialization system in Unity (SerializeReference), it doesn't handle well cases like that.

If you want to move a node or parameter class, you need to put a `MovedFrom` attribute to tell Unity where to find the previously serialized data like that:

```Csharp
using UnityEngine.Scripting.APIUpdating;

[System.Serializable, NodeMenuItem("Custom/Renamable"), MovedFrom(false, null, null, "RenamableNode")]
public class RenamableNode2 : BaseNode
{
...
```

There are improvements coming related to this on Unity side but unfortunately I can't do anything on my side to fix this :(

**Comment by LudiKha** [comment]
Ok, I think that should be enough to weather the worst of this! 👍
