### ISSUE TITLE
Vector2Int not correct property draw with attribute [ShowAsDrawer]

### ISSUE THREAD

**Issue by MilkyBrain** [alelievr/NodeGraphProcessor#162]
![image](https://user-images.githubusercontent.com/7694071/118784839-02b73400-b899-11eb-8c72-ffcbf0b5b64d.png)
![image](https://user-images.githubusercontent.com/7694071/118784986-1bbfe500-b899-11eb-9654-c264420a7c1c.png)

**Comment by alelievr** [comment]
Thanks for the bug report :) 

This issue should be fixed with this commit: https://github.com/alelievr/NodeGraphProcessor/commit/7d3e88da9817670b781ad07173ca6b3a41224c51
