### ISSUE TITLE
Node Inspector showing fields of non-selected node 

### ISSUE THREAD

**Issue by leissler** [alelievr/NodeGraphProcessor#168]
When selecting a node with an [ShowInInspector] attribute everything is fine and shown in the inspector.
However, if I then select a node that has no inspector fields, the ones from the other node are still shown. This is confusing, as the user/developer expects the inspector to show information about selected elements. 
When selecting a node without a node inspector, the inspector-area should be empty.

Also: There should be a possibility to show fields in both, the node inspector and the node itself. 
So [SerializeField, ShowInInspector] should be valid.

**Comment by alelievr** [comment]
Thanks for the report, the issue should be fixed in master: https://github.com/alelievr/NodeGraphProcessor/commit/e521898b566c3e22eaf58a86b1faf40027a85930 and https://github.com/alelievr/NodeGraphProcessor/commit/a60208b023cb55a4867b06e215bf61bb3aaf7d9b
