### ISSUE TITLE
ICreateNodeFrom - support inheritance 

### ISSUE THREAD

**Issue by thebne** [alelievr/NodeGraphProcessor#176]
I have a sequence of ScriptableObjects - A, B (extends A), C (extends A).
I want to drag A, B or C to the graph and create a separate, custom node for each.

Right now the API won't let me create nodes for A or B, because if `ICreateNodeFrom<A>` catches first, it will try to handle it: 
- if it succeeds, I am not able to create a custom node for B/C;
- if it fails, the loop stops and `ICreateNodeFrom<B>` / `ICreateNodeFrom<C>` never gets called.

I suggest this change, which is similar to Unity's `bool OnOpenAsset()`: 

```
					foreach (var kp in nodeTypePerCreateAssetType)
					{
						if (kp.Key.IsAssignableFrom(objectType))
						{
							try
							{
								var node = BaseNode.CreateFromType(kp.Value.nodeType, mousePos);
								if ((bool)kp.Value.initalizeNodeFromObject.Invoke(node, new[] { obj }))
								{
									AddNode(node);
									break;
								}
							}
							catch (Exception exception)
							{
								Debug.LogException(exception);
							}
						}
					}
```

**Comment by alelievr** [comment]
Yeah, I agree with that. I've pushed the modification in master: https://github.com/alelievr/NodeGraphProcessor/commit/7c5d23ae95728641d0b93edf1ce6e63c92d4d66a

Thanks a lot for the fix!

**Comment by thebne** [comment]
@alelievr I have noticed another issue that is related, and was wondering what you think about it:

in `BaseGraphView.cs`:
```
// We only add the type that implements the interface, not it's children
if (initializeFunction.DeclaringType == nodeInfo.type)
	nodeTypePerCreateAssetType[genericArgumentType] = (nodeInfo.type, initializeFunction);
```

My design (A, B extends A, C extends A) actually *assumes* that B also implements the interface (and overrides it if needed).
I ended up removing the if statement there for my version of the library, but giving you heads-up in case you want to change that as well.
