### ISSUE TITLE
Settings should be taken from hierarchy (remove DeclaredOnly flag)

### ISSUE THREAD

**Issue by thebne** [alelievr/NodeGraphProcessor#177]
in `BaseNodeView.cs`:
```
var fields = nodeTarget.GetType().GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
```

I believe this fits better, as it traverses through the hierarchy and allows inheriting settings while still showing them in the inspector:
```
var fields = nodeTarget.GetType().GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
```

**Comment by alelievr** [comment]
Good catch!

I fixed it in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/ac8a6a3007c39356db6a4b66e494b5249fe4f599
