### ISSUE TITLE
Custom Multiple Output ports are not working

### ISSUE THREAD

**Issue by m3rt32** [alelievr/NodeGraphProcessor#18]
Hey there, I've been trying to make a branching structure like a dialogue system. So, I've been trying to convert **CustomPortsNode** from multiple inputs to mulitple outputs. But whenever I do that, I can connect a single port to another node, though if I try to connect a second one, it throws a NullRefException as follows:

> NullReferenceException: Object reference not set to an instance of an object
> GraphProcessor.SerializableEdge.CreateNewEdge (GraphProcessor.BaseGraph graph, GraphProcessor.NodePort inputPort, GraphProcessor.NodePort outputPort) (at Assets/com.alelievr.NodeGraphProcessor/Utils/SerializableEdge.cs:53)

And in line 53, we have this:
![image](https://user-images.githubusercontent.com/3215742/61070198-c3a33680-a416-11e9-9db0-aba8b35eaee1.png)

I've tried to debug, in second port connection attempt, outputPort and owner is null.

**Behaviour Example:** (Doesn't connect 2nd one and throws the exception at above)

![image](https://media.giphy.com/media/J0I5bS2goWFuWLt2w0/giphy.gif)

This is the node that I've used, basically it is the same node as CustomPortDataNode, I just flipped input and outputs.
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using GraphProcessor;
using System.Linq;

[System.Serializable, NodeMenuItem("Custom/MultiPorts")]
public class CustomPortsNode : BaseNode
{
    [Input]
	public List< float >       	inputs;

	[Output]
	public List< float >		outputs; // TODO: custom function for this one

	List< object >				values;

	public override string		name => "CustomPorts";

    public override string      layoutStyle => "TestType";

    // We keep the max port count so it doesn't cause binding issues
    [SerializeField, HideInInspector]
	int							portCount = 1;

	protected override void Process()
	{
		// do things with values
	}

	[CustomPortBehavior(nameof(outputs))]
	IEnumerable< PortData > ListPortBehavior(List< SerializableEdge > edges)
	{
		portCount = Mathf.Max(portCount, edges.Count + 1);

		for (int i = 0; i < portCount; i++)
		{
			yield return new PortData {
				displayName = "In " + i,
				displayType = typeof(float),
				identifier = i.ToString(), // Must be unique
			};
		}
	}

	[CustomPortOutput(nameof(outputs), typeof(float))]
	void PullInputs(List< SerializableEdge > inputEdges)
	{
		//values = inputEdges.Select(e => e.passThroughBuffer).ToList();
	}

	[CustomPortInput(nameof(inputs), typeof(float))]
	void PushOutputs(List< SerializableEdge > connectedEdges)
	{
		// Values length is supposed to match connected edges length
		//for (int i = 0; i < connectedEdges.Count; i++)
		//	connectedEdges[i].passThroughBuffer = values[i];
	}
}

```

**Comment by m3rt32** [comment]
Update: I believe I might have a solution, I've debugged further and found that in **BaseGraphView.cs:**
```c#			
if (serializeToGraph)
{
				NodePort inputPort = inputNodeView.nodeTarget.inputPorts.FirstOrDefault(o => o.portData.identifier == inputPortView.portData.identifier);
				NodePort outputPort = outputNodeView.nodeTarget.outputPorts.FirstOrDefault(o => o.portData== outputPortView.portData);

				e.userData = graph.Connect(inputPort, outputPort);
}
```
This line is 
`NodePort outputPort = outputNodeView.nodeTarget.outputPorts.FirstOrDefault(o => o.portData== outputPortView.portData);` causing that issue. So I've changed it to **o.portData.identifier== outputPortView.portData.identifier**. And now it seems to be working for output ports.

Do you see any setbacks or side effects that it will cause ? If not, I'll send a PR.

**Comment by alelievr** [comment]
Hi, indeed there is an error in the code that finds the output port, it must use the identifier to find the port. I did a fixed in master for this: https://github.com/alelievr/NodeGraphProcessor/commit/33901bf3b040f844182b305fe2242773c0812dcb where i use GetPort instead of iterating over all ports manually.

Thanks for reporting the issue and taking the time to investigate :)

**Comment by m3rt32** [comment]
Thank you for your interest as well :) Good solution, I'll pull and see how it goes. For know I am closing the issue, if something like that occurs I'll open it back up. Cheers!
