### ISSUE TITLE
How to get this working

### ISSUE THREAD

**Issue by MMJM** [alelievr/NodeGraphProcessor#28]
Hi, 

I've tried to get this project running in Unity 2019.2 and 2020.1 but I get loads of errors

I copied the project to my Unity project Assets folder and it imported. Then I get about 200 errors

Things like

The type or namespace name 'GraphProcessor' could not be found (are you missing a using directive or an assembly reference?)	D:\Unity\Test2\Assets\NodeGraphProcessor-master\Assets\Examples\DefaultNodes\Nodes\TextNode.cs	4	Active

Generally a lot of missing stuff. Where is all this extra stuff?

Thanks

**Comment by alelievr** [comment]
Hello, the project works fine with 2019.2, maybe you are missing the reference to the assembly definition file ? That could explain why the compiler does not find the namespace.
You can have more info here: https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by MMJM** [comment]
Thanks for the reply I got the project running.

How does the runtime editor work? 

I’d like to use the editor outside Unity in a built project

**Comment by alelievr** [comment]
If you mean the graph editor, it's not possible to use it outside of the Unity Editor since it's build on top of the [GraphView ](https://docs.unity3d.com/ScriptReference/Experimental.GraphView.GraphView.html) library which is editor only,

But the graph processing works in build.

**Comment by andybak** [comment]
I wonder if this will get moved out of the Editor namespace once UI Elements for runtime is released. That's allegedly going to be released in preview this year.

**Comment by alelievr** [comment]
Not sure about that :/
