### ISSUE TITLE
class CustomConvertions -> InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by BEmreGurkan** [alelievr/NodeGraphProcessor#30]
Hi,

i try to add code to the class. for example i wanna convert int32 to string. i write the code in CustomConvertions class.

![Ekran Resmi 2019-11-15 14 00 50](https://user-images.githubusercontent.com/57793286/68939302-4e26e880-07b1-11ea-80d0-b71d094614ba.png)

Seems to be working.

![graph](https://user-images.githubusercontent.com/57793286/68940551-82e86f00-07b4-11ea-9aa7-4040aa5534d1.gif)

But when i try to run, show this error : InvalidCastException: Specified cast is not valid.

I don't understand. It's same convert vector4 to float. But my code doesn't work.

Please help us!
Thank you =D

**Comment by TeorikDeli** [comment]
Well, as I understand from the com.alelievr.NodeGraphProcessor/Runtime/Elements/NodePort.cs:94 line (// TODO: TypeAdapter convertion method here) this conversion part hasn't finished yet. So, right now it only works in the graphview as visually? 🤔

**Comment by alelievr** [comment]
Hey,

There was indeed an issue in the convertion code when ports have a CustomPortBehavior attribute attached (the wrong type was sent to the convertion function in that case).
I fixed it in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/98fb975a7b70a2798e053cdab8037a5298696523 so it should work now :)
