### ISSUE TITLE
ListView on the node

### ISSUE THREAD

**Issue by cuddlecats** [alelievr/NodeGraphProcessor#34]
Hello, thanks for the conditional example, it was very helpful.
Can you show me some examples of how can I add some list or array to the node? 

Thanks for the support, Mikhail.

**Comment by alelievr** [comment]
Hello,

You can do anything you want in the custom view of a node (you can add UIElement stuff on the node), here is the doc: https://github.com/alelievr/NodeGraphProcessor/wiki/Node-scripting-API#custom-view.

And the listview in UIElement can be implemented as in the unity doc: https://docs.unity3d.com/ScriptReference/UIElements.ListView.html
