### ISSUE TITLE
Node edges persist after removal

### ISSUE THREAD

**Issue by Taenebron** [alelievr/NodeGraphProcessor#37]
I'm trying to traverse trough nodes via functions like:
`outputPorts.FirstOrDefault(n => n.fieldName == "outNodes").GetEdges().Select(e => e.inputNode as BaseNode)` to later conduct operations/process nodes on demand in my implementation.

When i disconnect nodes from graphs in graph editor, they do not disappear from outputPorts. So they are still returned via `outputPorts.FirstOrDefault` I mentioned. 

**Example:** when I connect output to node A and B - and then remove link to node B and add C: ABC will be returned (instead of AC).
**Example 2:** adding node and removing it will sill return a node, even if output has no edges.

After code recompilation (after any changes to class files), everything updates to correct state and removed nodes disappear from outputPorts.

Something I may be doing wrong, bug... or something I need to do?
I use manual, node traversal as I use implementation that depends on user input. Maybe this approach is causing issue and I need to use processor?

**Comment by dannymate** [comment]
Do you figure out what the issue was?
