### ISSUE TITLE
Request: Create GitHub Release Please

### ISSUE THREAD

**Issue by favoyang** [alelievr/NodeGraphProcessor#41]
Hi @alelievr,

Thanks for submitting the package to the openupm platform. You need [create a GitHub release](https://openupm.com/docs/adding-upm-package.html#handling-the-repository-without-git-tags) (git tag) to make it work. The git tag name shall match the version string in the package.json, in your case `0.4.0`.

I also send PR https://github.com/alelievr/NodeGraphProcessor/pull/40 for documentation update.

**Comment by alelievr** [comment]
Hi @favoyang,

Thanks for the documentation PR, I just merged it :)
I just added a tag here: https://github.com/alelievr/NodeGraphProcessor/tree/0.4.0 Is it okay ?

**Comment by favoyang** [comment]
Great, it works. Thanks for your efforts.
