### ISSUE TITLE
Undo stops working

### ISSUE THREAD

**Issue by GangstaHikka** [alelievr/NodeGraphProcessor#49]
Represent: 
Open some graph.
Change some node position.
Ctrl+z. Working well.
Close graph.
Open another graph.
Change some node position.
Ctrl+z. Not working.

Console error:

ArgumentNullException: Value cannot be null.
Parameter name: identifier
UnityEditor.Undo.RegisterCompleteObjectUndo (UnityEngine.Object objectToUndo, System.String name) (at <e2353c5c084f4b5a9d8ead9c6b8ffaa2>:0)
GraphProcessor.BaseNodeView.SetPosition (UnityEngine.Rect newPos) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:567)
GraphProcessor.BaseNodeView.InitializeView () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:123)
GraphProcessor.BaseNodeView.Initialize (GraphProcessor.BaseGraphView owner, GraphProcessor.BaseNode node) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:80)
GraphProcessor.BaseGraphView.AddNodeView (GraphProcessor.BaseNode node) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:615)
GraphProcessor.BaseGraphView.InitializeNodeViews () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:532)
GraphProcessor.BaseGraphView.ReloadView () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:473)
UnityEditor.Undo.Internal_CallUndoRedoPerformed () (at <e2353c5c084f4b5a9d8ead9c6b8ffaa2>:0)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()

**Comment by alelievr** [comment]
Hey, thanks for the report it should be fixed in bc578f486cd9a136ad72b312077a13625f5918ab
