### ISSUE TITLE
InvalidCastException: Specified cast is not valid when having a multiple input

### ISSUE THREAD

**Issue by molocai** [alelievr/NodeGraphProcessor#5]
```csharp
 [Input(name = "Multi float", allowMultiple = true)]
 public IEnumerable<float> inputsFloat;
```

![image](https://user-images.githubusercontent.com/7241275/50908762-af13c080-142a-11e9-961a-8001c56b03dd.png)

Processing the graph causes this exception :
```
InvalidCastException: Specified cast is not valid.
(wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure)
GraphProcessor.NodePort.PushData () (at Assets/NodeGraphProcessorRuntime/Core/Elements/NodePort.cs:101)
GraphProcessor.NodeOutputPortContainer+<>c.<PushDatas>b__1_0 (GraphProcessor.NodePort p) (at Assets/NodeGraphProcessorRuntime/Core/Elements/NodePort.cs:159)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
GraphProcessor.NodeOutputPortContainer.PushDatas () (at Assets/NodeGraphProcessorRuntime/Core/Elements/NodePort.cs:159)
GraphProcessor.BaseNode.OnProcess () (at Assets/NodeGraphProcessorRuntime/Core/Elements/BaseNode.cs:159)
```

Apparently the lambda is not used to dealing with IEnumerable in inputs

**Comment by alelievr** [comment]
Yes, to be able to connect two types that can't be implicitly casted (float vs IEnumerable<float>) you need to specify a custom port function (CustomPortInput or CustomPortOutput), this function gives you in parameter the list of all edges connected to the port so you have the full control. The passThroughBuffer inside the edge purpose is to be used by custom port function to communicate custom values to the edges.
Btw, I added a better error message message in 322ea0f

**Comment by OneManMonkeySquad** [comment]
(This should really be part of the manual)
