### ISSUE TITLE
undo very slow in unity 2019.3.5f1

### ISSUE THREAD

**Issue by meowao** [alelievr/NodeGraphProcessor#51]
when i open any graph and move node position, press ctrl+z. 
it's need wait over 1 min then the node recover to origin position.

unity version : 2019.3.5f1

**Comment by alelievr** [comment]
Hello,

I can't repro on my side with 2019.3.6f1. Do you have any modifications on top of the package ? or maybe you are working on a very big graph ?

In any case, can you try to see what's taking time with the Unity Profiler ?

**Comment by meowao** [comment]
> Hello,
> 
> I can't repro on my side with 2019.3.6f1. Do you have any modifications on top of the package ? or maybe you are working on a very big graph ?
> 
> In any case, can you try to see what's taking time with the Unity Profiler ?

thanks for your reply, i found that it should be caused by other plugins
