### ISSUE TITLE
Name collision with Doozy assets

### ISSUE THREAD

**Issue by githappens** [alelievr/NodeGraphProcessor#52]
Hi,
I just pulled this repo into my project and noticed that some of the example scripts share the same name as other included libraries:
`Assets/Plugins/Doozy/Engine/Nody/Models/Graph.cs(261,28): error CS0039: Cannot convert type 'Doozy.Engine.Nody.Models.Node' to 'StartNode' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion`
This can be quickly solved by moving the example scripts into a different namespace.

**Comment by githappens** [comment]
[This PR](https://github.com/alelievr/NodeGraphProcessor/pull/53) solved it for me

**Comment by alelievr** [comment]
#53 merged! Thanks for your help :)
