### ISSUE TITLE
Can't add GameObject parameters

### ISSUE THREAD

**Issue by johanhelsing** [alelievr/NodeGraphProcessor#57]
Cloned the project and opened in 2019.3.15.

If click on the `ExposedGetProperties` example, I can see the exposed gameobject property, however, if I try to add more parameters, they don't appear in the inspector.

Tried restarting the editor, but it doesn't help.

Other types of parameters seem to work.

**Comment by FruitJuice** [comment]
Having same issue. I'm using 2019.3.12f1
For me in the provided Example scene the GameObject property doesn't appear under Exposed Parameters even though in the graph it exists. It isn't set to hide in the inspector either.

**Comment by alelievr** [comment]
Hello,

I managed to reproduce this issue and submitted a fix here: https://github.com/alelievr/NodeGraphProcessor/commit/dd3e6bfcd46ab2b5ca36a3fa8a7b544a5e02cb8d

Thanks for the report :)
