### ISSUE TITLE
How do you use it at runtime?

### ISSUE THREAD

**Issue by Ruchi12377** [alelievr/NodeGraphProcessor#59]
Hello.
I'd like to use this feature to do some processing at runtime, but I don't know how to do it.
But I've looked at various parts of it, including "read.me", but I don't know how to do it.
I'd appreciate it if you could tell me how to do it.
It's a translation from Japanese, so the text may not be correct. Sorry...

**Comment by alelievr** [comment]
Hello,

If you open the SampleScene in the repository, there is a `RuntimeGraph` object in it which execute a graph at runtime that log in the console the result of an operation:
![RuntimeGraph](https://user-images.githubusercontent.com/6877923/87039278-393f0f80-c1ef-11ea-9247-b691c1ca851b.gif)
You can find this script here: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Scenes/RuntimeGraph.cs

And this is the part of the graph that prints the result of the operation:
![image](https://user-images.githubusercontent.com/6877923/87039484-7a372400-c1ef-11ea-94d7-0e773598ec2d.png)

**Comment by Ruchi12377** [comment]
Thank you for going out of your way to explain this to me. :)
