### ISSUE TITLE
ToolbarView AddButton doesn't seem to be adding any buttons

### ISSUE THREAD

**Issue by MostHated** [alelievr/NodeGraphProcessor#64]
Hey again,
    I was beginning to experiment with things, so I create a new Window/View/Toolbar, following the Custom Toolbar example, but then I noticed that even in the example, I don't see any sort of custom toolbar?
I am assuming it should be up there near Center, Show Processor, etc, etc?

<img src="https://i.imgur.com/IJi6NO4.png" width="650" />

I went to try and add a new one as follows:

```cs
    public class WaypointNodeManagerToolbar : ToolbarView
    {
        public WaypointNodeManagerToolbar(BaseGraphView graphView) : base(graphView)
        {
        }

        protected override void AddButtons()
        {
            // Add the hello world button on the left of the toolbar
            AddButton("Hello !", () => Debug.Log("Hello World"), false);
            AddButton("Create new Waypoint", () => Debug.Log("Creating new waypoint"));

            // add the default buttons (center, show processor and show in project)
            base.AddButtons();
        }
    }
```
This is what I end up with:

 <img src="https://i.imgur.com/SVyg70Y.png" width="650" />
I feel like I might be missing something silly? Perhaps it's related to 2020.1.0b15. I will try the example in a lesser version to compare.

Thanks,
-MH

**Comment by alelievr** [comment]
Hello,
There was indeed an issue in the AddButtons() code of the ToolBarView (it was deleting existing buttons from the list before adding new ones).
The issue should be fixed in this commit: 9ccce050ee63d62a87cd544bf10751b7783686dc

Thanks for the detailed bug report!
