### ISSUE TITLE
Wiki's default graph window example is outdated

### ISSUE THREAD

**Issue by Eldemarkki** [alelievr/NodeGraphProcessor#66]
I found [this example](https://github.com/alelievr/NodeGraphProcessor/wiki/Graph-Window-API) from the wiki while playing around, and it gave an error saying "DefaultGraphWindow does not implement inherited abstract member 'BaseGraphWindow.InitializeWindow(BaseGraph)". 

Apparantly Initialize() has been renamed to InitializeWindow(). I think that should be updated in the wiki page too. I would also remove the unnecessary using directives which are `System.Collections` and `System.Collections.Generic`, so that the example can be as clutter-free as possible.

**Comment by alelievr** [comment]
Hello, thanks for your feedback, I've updated the doc and example should compile now :)
