### ISSUE TITLE
Add branch for unity package manager

### ISSUE THREAD

**Issue by MoeLang** [alelievr/NodeGraphProcessor#7]
Unity package manager surport git url sync.
I forked and created new branch for this code,  add this line in manifest.json.

"com.alelievr.node-graph-processor": "https://github.com/MoeLang/NodeGraphProcessor.git#upm",

Can this repo add such a branch? Thanks!

**Comment by alelievr** [comment]
I was wondering about either doing this or a separate repository with the dev environment and a submodule pointing to this repository. For now i'll do a separate branch so i can do releases when i want but it might change in the future.
Here's the branch: https://github.com/alelievr/NodeGraphProcessor/tree/upm
