### ISSUE TITLE
An issue with dragging in assets. Probably a bug in unity's shader graph that we'll need to handle

### ISSUE THREAD

**Issue by cbaggers** [alelievr/NodeGraphProcessor#71]
When dragging an asset over the graph view Unity spams `Undo.undoRedoPerformed`. A real pain when you try to use nodes with ObjectFields.

It manifests in two different ways ~~depending on if it's a temp graph or not~~.

Here is the case where the graph is loaded from an asset.

![graphUndoRedoIssue0](https://user-images.githubusercontent.com/1579326/88312206-23af0700-cd12-11ea-8848-4b7447a2108a.gif)

And here is one of the stack traces (they all seem to be the same).

```
ArgumentNullException: Value cannot be null.
Parameter name: identifier
UnityEditor.Undo.RegisterCompleteObjectUndo (UnityEngine.Object objectToUndo, System.String name) (at <a20a50bbfaff4193bf6ba6b262f9a71f>:0)
GraphProcessor.BaseGraphView.RegisterCompleteObjectUndo (System.String name) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:968)
GraphProcessor.BaseNodeView.SetPosition (UnityEngine.Rect newPos) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:646)
GraphProcessor.BaseNodeView.InitializeView () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:153)
GraphProcessor.BaseNodeView.Initialize (GraphProcessor.BaseGraphView owner, GraphProcessor.BaseNode node) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseNodeView.cs:81)
GraphProcessor.BaseGraphView.AddNodeView (GraphProcessor.BaseNode node) (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:736)
GraphProcessor.BaseGraphView.InitializeNodeViews () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:635)
GraphProcessor.BaseGraphView.ReloadView () (at Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseGraphView.cs:567)
UnityEditor.Undo.Internal_CallUndoRedoPerformed () (at <a20a50bbfaff4193bf6ba6b262f9a71f>:0)
```

~~The case for temporary graphs is a little different. This is the one that is causing me the most issues as I use temp graphs.~~
The second case is a little different.
> Note: I needed to restart the editor after getting the first kind of error before this one showed up.

![graphUndoRedoIssue1](https://user-images.githubusercontent.com/1579326/88313106-4f7ebc80-cd13-11ea-89aa-990488c92486.gif)

Here we do actually get an undo before it start spamming the callback. In the first part of the video I move a node twice (it's hard to see but I do briefly let go of it when it's on the left). In the second part of the video I spawn a node to show that the spurious undo removes the node.

**Comment by cbaggers** [comment]
I think that the first version is down to the BaseGraphView not being un-subscribed from the `Undo.undoRedoPerformed` event. The null-ref is then due to the graph (quite correctly) being null as it was closed

**Comment by cbaggers** [comment]
Ah. When we spawn a node (in the temp graph) `OnBeforeSerialize()` is being called before the graph's `nodes` list is updated. Which means it's despawning when `undoRedoPerformed` is called and `ReloadView` calls `Deserialize`

That makes sense.

**Comment by cbaggers** [comment]
It was tricky but I can confirm that I can get the second behavior with a normal graph (not a temporary one). It was harder to reproduce as you can't see the problem if either the null ref error from above happens, or if https://github.com/alelievr/NodeGraphProcessor/issues/72 happens.

**Comment by alelievr** [comment]
I think I found the Undo/Redo issue: I pushed a fix in this commit: https://github.com/alelievr/NodeGraphProcessor/commit/84bb92cbcf253a0f0db2760967a6c52a7fd6eefa

Btw, asset drag and drop is something I want to support but I didn't looked into it yet

**Comment by cbaggers** [comment]
Awesome work, looks good from my end too.

**Comment by alelievr** [comment]
👍 I added a card to track the drag and drop task here: https://github.com/alelievr/NodeGraphProcessor/projects/2#card-42476359 so i'll close this issue.
