### ISSUE TITLE
Potential Issue: Graph is serialized constantly whilst the inspector is active

### ISSUE THREAD

**Issue by cbaggers** [alelievr/NodeGraphProcessor#72]
This one surprised me whilst I was looking into the Unity undo issue. 

If you click on a graph in the project treeview (so that it is selected and the `GraphInspector` is showing in the inspector) `BaseGraph.OnBeforeSerialize()` will be called constantly.

This is easiest to see if you add a debug.log to `BaseGraph.OnBeforeSerialize()`. 

This will probably be an issue when graph sizes are large enough that serializing them every frame would be noticable

**Comment by cbaggers** [comment]
Can confirm that it's being driven in part by `OnInspectorUpdate` which is called [10 times a second](https://docs.unity3d.com/ScriptReference/EditorWindow.OnInspectorUpdate.html)
```
UnityEngine.Debug:Log(Object)
GraphProcessor.BaseGraph:OnBeforeSerialize() (at Assets/com.alelievr.NodeGraphProcessor/Runtime/Graph/BaseGraph.cs:360)
UnityEditor.HostView:OnInspectorUpdate()
```

**Comment by alelievr** [comment]
Yeah it's a known issue, unity does this for every selected scriptable object. There is a card for this one on the project: https://github.com/alelievr/NodeGraphProcessor/projects/2#card-34943052. It's just a dirty flag but it will avoid the overhead of this function being called too ofen

**Comment by cbaggers** [comment]
Oh nice, I had missed that. I'll close this as it's tracked over there.
Cheers!
