### ISSUE TITLE
Provide values/literals directly next to the port

### ISSUE THREAD

**Issue by JefferiesTube** [alelievr/NodeGraphProcessor#75]
On more complex nodes, it can become very hard to see, which port receives which value. Any plans (or a workaround) to enable this (see this screenshot from the unity forum https://forum.unity.com/attachments/upload_2018-1-18_21-14-48-png.263065/)

**Comment by alelievr** [comment]
Hello, I believe this is a duplicate of https://github.com/alelievr/NodeGraphProcessor/issues/65

**Comment by alelievr** [comment]
#65 is resolved so this issue follows :) 
You can now use [ShowAsDrawer] attribute on input fields to show a small drawer beside the port (like in SG)
