### ISSUE TITLE
(Runtime graph) Need to execute 2 time for parameter to get set?

### ISSUE THREAD

**Issue by jejelite** [alelievr/NodeGraphProcessor#76]
![image](https://user-images.githubusercontent.com/20047579/88719718-baecd380-d0f1-11ea-9765-45493a340317.png)

Im messing around and familiarizing myself with the api (Nice job to the author by the way). I'm trying to execute the following graph in runtime using the base processor for some reason i always get a null reference of the parameters on the first go but after that everything working has it should.

here is the runtime code,
`public class Testing : SerializedMonoBehaviour
{
    [SerializeField] private TreeBehaviorGraph graph = null;
    [SerializeField] private ProcessGraphProcessor processor;

    [BoxGroup("Entities")]
    public RPGEntity player;
    [BoxGroup("Entities")]
    public RPGEntity AI;

    private void Start()
    {
        graph = ScriptableObject.Instantiate(graph);

        if (graph != null)
            processor = new ProcessGraphProcessor(graph);
    }

    [Button("Init")]
    public void Init()
    {
        graph.SetParameterValue("ThisEntity", player);
        graph.SetParameterValue("Target", AI);
    }

    [Button("Execute")]
    public void Execute()
    {
        if (graph != null)
        {
            Init();
            processor.Run();
        }
    }
}`

**Comment by alelievr** [comment]
Hello,

Can you send the error stacktrace you have in the console?

**Comment by jejelite** [comment]
The error is a missing reference in this case it will happen in "HasLessHealthThenX" but i could change the first node evaluated and i would have the same result.

Error StackTrace :

`System.NullReferenceException: Object reference not set to an instance of an object
  at FracLib.NodeGraph.TreeBehavior.HasLessHealthThenX.Evaluate () [0x00008] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Assets\_Test_TreeBehavior\HasLessHealthThenX.cs:21 
  at FracLib.NodeGraph.TreeBehavior.SequenceNode.Evaluate () [0x0001a] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Assets\FracLib\NodeGraph\TreeBehavior\Nodes\Composite\SequenceNode.cs:19 
  at FracLib.NodeGraph.TreeBehavior.SelectorNode.Evaluate () [0x00018] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Assets\FracLib\NodeGraph\TreeBehavior\Nodes\Composite\SelectorNode.cs:18 
  at FracLib.NodeGraph.TreeBehavior.StartNode.Evaluate () [0x00018] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Assets\FracLib\NodeGraph\TreeBehavior\Nodes\StartNode.cs:26 
  at FracLib.NodeGraph.TreeBehavior.StartNode.Process () [0x00001] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Assets\FracLib\NodeGraph\TreeBehavior\Nodes\StartNode.cs:19 
  at GraphProcessor.BaseNode.<OnProcess>b__52_0 () [0x00000] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Library\PackageCache\com.alelievr.node-graph-processor@0.7.1\Runtime\Elements\BaseNode.cs:356 
  at GraphProcessor.ExceptionToLog.Call (System.Action a) [0x00002] in C:\Users\JEJELITE\Documents\GitHub\ObsoletePrototype\ObsoleteProto\Library\PackageCache\com.alelievr.node-graph-processor@0.7.1\Runtime\Utils\ExceptionToLog.cs:14 
UnityEngine.Debug:LogError(Object)
GraphProcessor.ExceptionToLog:Call(Action) (at Library/PackageCache/com.alelievr.node-graph-processor@0.7.1/Runtime/Utils/ExceptionToLog.cs:19)
GraphProcessor.BaseNode:OnProcess() (at Library/PackageCache/com.alelievr.node-graph-processor@0.7.1/Runtime/Elements/BaseNode.cs:356)
GraphProcessor.ProcessGraphProcessor:Run() (at Library/PackageCache/com.alelievr.node-graph-processor@0.7.1/Runtime/Processing/ProcessGraphProcessor.cs:39)
Testing:Execute() (at Assets/_Test_TreeBehavior/Testing.cs:38)
System.Reflection.MethodBase:Invoke(Object, Object[])
Sirenix.OdinInspector.Editor.Drawers.DefaultMethodDrawer:InvokeButton() (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/DefaultMethodDrawer.cs:388)
Sirenix.OdinInspector.Editor.Drawers.DefaultMethodDrawer:DrawNormalButton() (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/DefaultMethodDrawer.cs:237)
Sirenix.OdinInspector.Editor.Drawers.DefaultMethodDrawer:DrawPropertyLayout(GUIContent) (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/DefaultMethodDrawer.cs:149)
Sirenix.OdinInspector.Editor.OdinDrawer:DrawProperty(GUIContent) (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:176)
Sirenix.OdinInspector.Editor.InspectorProperty:Draw(GUIContent) (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:602)
Sirenix.OdinInspector.Editor.InspectorUtilities:DrawPropertiesInTree(PropertyTree) (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Misc/InspectorUtilities.cs:418)
Sirenix.OdinInspector.Editor.PropertyTree:Draw(Boolean) (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/PropertyTree.cs:308)
Sirenix.OdinInspector.Editor.OdinEditor:DrawTree() (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:93)
Sirenix.OdinInspector.Editor.OdinEditor:DrawOdinInspector() (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:215)
Sirenix.OdinInspector.Editor.OdinEditor:OnInspectorGUI() (at X:/Repositories/sirenix-development/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinEditor.cs:85)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by alelievr** [comment]
So, If I understand correctly the crash happens when you do
```CSharp
var p = graph.GetParameterValue("...");
```
in HasLessHealthThenX.cs:21 ?
Can you also check that the graph is not null? It's very unlikely but who knows

**Comment by alelievr** [comment]
Hum, it's weird I tried to repro with a simple scriptable object that I expose as a parameter and then I run the graph from a script but it works correctly.

Just as a sanity check: what happens if you connect a Debug.Log node to the parameter node "This Entity"? Is it null on the first run or have the correct value?

**Comment by jejelite** [comment]
The Debug.log reflect the same problem, the entity appear null on the first run, if i rerun the graph it's set correctly

**Comment by alelievr** [comment]
Then maybe it's a compute order problem, can you check that the nodes are processed in the correct order? you can enable debug mode on the node to display the compute order:
![image](https://user-images.githubusercontent.com/6877923/89063452-82a2fa80-d368-11ea-9d2f-58ed5126148c.png)

If it's not that I really don't know. Maybe if you don't mind you can send me your project or a unity pacakge if it's not too big for a repro?

**Comment by jejelite** [comment]
Ok, sry for the delay i took a week off , the problem is not from the compute order. I just sent you a invite to a repo with a package containing the example and code we used for testing the api if you want to take a look.

**Comment by alelievr** [comment]
👍 I'll take a look

**Comment by alelievr** [comment]
So I took a look and there is indeed something in your code that breaks evaluation of the graph (from SequenceNode):
```CSharp
            bool anyChildRunning = false;
            foreach (TreeBehaviorNode node in GetChildren())
            {
==>            switch (node.Evaluate())
                {
                    case NodeState.FAILURE:
                        nodeState = NodeState.FAILURE;
                        return nodeState;
```

This switch line call the Evalute on a node that have not yet been evaluated, but this also means that this node was not ready to be executed. In this precise case, the parameter node hasn't been processed yet when we process the `SequenceNode` so it's value is not yet sent to the `HasLessHealthThenX` node.
This explains why on the first run, you don't have the correct value in your node (your code basically shortcuts the graph execution order and thus gives in incorrect results).

Note that doing this also doesn't work because you are using the `ProcessGraphProcessor` in your Testing.cs which will result in the execution of **all** the nodes in the graph, completely ignoring the logic you have in your conditional nodes.

I think the correct solution in this case is to modify the ProcessGraphProcessor or write a new one. You have an example of conditional processing in this repo here: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/Examples/ConditionalGraph/ConditionalProcessor.cs#L83
It's probably more complicated than what you need but it should be a good example.

**Comment by jejelite** [comment]
Thanks for the answer! Will look into implementing a custom GraphProcessor for a ThreeBehavior logic. I was initially hoping to avoid that that why i try what i did but i for some reason didn't think that the node would not be set properly because of that.

Thanks again
