### ISSUE TITLE
Dragging Node into Stack breaks moving nodes until graph is reopened

### ISSUE THREAD

**Issue by hybridherbst** [alelievr/NodeGraphProcessor#84]
Using latest version, dragging a Node into Stack breaks moving nodes until graph is reopened:

![20200905-141459](https://user-images.githubusercontent.com/2693840/92304865-3740c500-ef82-11ea-9c03-0320ce78dbff.gif)

**Comment by hybridherbst** [comment]
Might be a Unity regression, seems to work fine in 2019.4.
Reported as Case 1275569 [Regression][GraphView] Dragging node into Stack node prevents further manipulation

**Comment by alelievr** [comment]
Closing the issue as it doesn't seems to be fixable on NGP side.
The issue will apparently only be fixed for 2020.2+

**Comment by hybridherbst** [comment]
Yep, seems like it. For future reference:
https://issuetracker.unity3d.com/product/unity/issues/guid/1275569
