### ISSUE TITLE
Feature: Event for changing order of nodes in StackedNode

### ISSUE THREAD

**Issue by hybridherbst** [alelievr/NodeGraphProcessor#88]
Not sure if there is, but seems currently there's no way to get an event for changed node order in a stacked node, unless going through the guids manually in some other event? Not sure which one that would be though... any idea?

**Comment by alelievr** [comment]
That should do: https://github.com/alelievr/NodeGraphProcessor/commit/f91d44b909e692d28c864d8c4f7f164f82aa8fe8 let me know if you have any issue with it.

![StackDrag](https://user-images.githubusercontent.com/6877923/92516034-dda3f900-f214-11ea-9df0-e7a5054feb2c.gif)
