### ISSUE TITLE
Question: Why does ToolbarView use IMGui and not UIElements?

### ISSUE THREAD

**Issue by hybridherbst** [alelievr/NodeGraphProcessor#89]
As per the title, that feels a bit inconsistent. Plus, it makes it harder to add actually useful UIElements stuff to it (e.g. search bars).
Workaround is of course to just use a different toolbar implementation, just wondering why it was done this way.

**Comment by alelievr** [comment]
There is no real reason behind this, it was few years ago when I started this project I couldn't get the UIElement toolbar to work no matter what I tried so I decided to implement the ImGUI version waiting for a fix.

It stayed like this until today 😅

**Comment by alelievr** [comment]
feature improvement tracked here: https://github.com/alelievr/NodeGraphProcessor/projects/2#card-33750520
