### ISSUE TITLE
Arrays, or Groups Feature

### ISSUE THREAD

**Issue by mlflabs** [alelievr/NodeGraphProcessor#93]
Hello, just wondering if there are any plans for groups, or arrays.

I noticed stacks, but besides the visual implementation, i can't seem to access an array of nodes in a stack

Or maybe is there another style of visual coding where multiple nodes can be grouped together.

any suggestions, or even some direction where to look would be great.

**Comment by alelievr** [comment]
Hey!

Groups already exists but it's the standard GraphView implementation:
![image](https://user-images.githubusercontent.com/6877923/93030517-fb61cb80-f623-11ea-9a3d-703663e46b26.png) you can create them with the context menu in the graph

I have no plan to add new "containers" right now.

Note that you can access the nodes in a stack with this API: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Elements/BaseStackNode.cs#L30 which gives you the GUID of the nodes, you can then get the node back using the `nodesPerGUID` field like I do here: https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Editor/Views/BaseStackNodeView.cs#L59

**Comment by mlflabs** [comment]
Thank you for the reply

Based on the info, stacks should work well,

thanks and keep it up.

Mike
