### ISSUE TITLE
Graph FSM. Recursion error while updating compute order

### ISSUE THREAD

**Issue by Mefodei** [alelievr/NodeGraphProcessor#97]
Hello there.

im trying to use your graph as FSM logic tree, but have some troubles.
First of all is graph limitation to use circle binding between ports

![](https://i.gyazo.com/ac8c0b5d404ee46aedad24a55a003e8a.png)

![](https://i.gyazo.com/383f6e4899c521080c20ec630e8e234a.png)

**Comment by alelievr** [comment]
Hello,

I think you're using an old version, the current compute order code handle this case relatively well (it doesn't crash/freeze but set the  node compute order to -2): https://github.com/alelievr/NodeGraphProcessor/blob/master/Assets/com.alelievr.NodeGraphProcessor/Runtime/Graph/BaseGraph.cs#L435

If you upgrade it should fix your issues

**Comment by Mefodei** [comment]
Thx, update helped
