### ISSUE TITLE
layer mask support

### ISSUE THREAD

**Issue by Bezarius** [alelievr/NodeGraphProcessor#99]
Layers masks  currently not supported in the inspector.  https://prnt.sc/upjgiq

**Comment by alelievr** [comment]
Hello, I added the feature in 127bd250d814c0a5693d7a22f6f0829067bbd9ba

![image](https://user-images.githubusercontent.com/6877923/94557157-7c44d800-025e-11eb-9c1d-2a7e22899186.png)
